services:
  tei-server:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.6
    container_name: tei-server
    ports:
      - "6500:80"
    networks:
      - ecommerce_network
    volumes:
      - ./data:/data
    # Highlight-start
    command: --model-id BAAI/bge-large-en-v1.5
    # Xenova maps BGE models perfectly into ONNX format for CPU usage
    #command: --model-id Xenova/bge-large-en-v1.5


networks:
  ecommerce_network:
    external: true
    name: ecommerce_network