events {}

http {

    upstream grafana {
        server grafana:3000;
    }

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name pi-home-01.architecture.caradhras.io;

        ssl_certificate     /etc/nginx/certs/certificate.crt;
        ssl_certificate_key /etc/nginx/certs/private-no-key.key;

        location / {
            proxy_pass http://grafana/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}