services:
  db-01:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "${PG_DB01_PORT:-5432}:5432"
    volumes:
      - postgres_data_01:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  db-02:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "${PG_DB02_PORT:-5433}:5432"
    volumes:
      - postgres_data_02:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  #db-03-vector:
  #  image: pgvector/pgvector:pg16
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres
  #    - POSTGRES_DB=postgres
  #  ports:
  #    - "5434:5432"
  #  volumes:
  #    - postgres_data_03:/var/lib/postgresql/data
  #  networks:
  #    - ecommerce_network

volumes:
  postgres_data_01:
  postgres_data_02:
  #postgres_data_03:

networks:
  ecommerce_network:
    external: true
    name: ecommerce_network