[SERVICE]
    Flush                     1
    Log_Level                 info
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M
    Parsers_File              parsers.conf

# Docker container logs
[INPUT]
    Name                tail
    Tag                 docker
    Path                /var/lib/docker/containers/*/*-json.log
    Parser              docker
    Mem_Buf_Limit       50MB
    Refresh_Interval    10
    Skip_Long_Lines     On
    Read_from_Head      true


# Parse the JSON contained inside the Docker "log" field
[FILTER]
    Name                parser
    Match               docker
    Key_Name            log
    Parser              app_json
    Reserve_Data        On
    Preserve_Key        Off


# Keep only logs that contain app_name
[FILTER]
    Name                grep
    Match               docker
    Regex               app_name .+


# Create a tag according to app_name
[FILTER]
    Name                rewrite_tag
    Match               docker
    Rule                $app_name ^go-inventory-v2$  go-inventory-v2  false
    Rule                $app_name ^go-order-v2$      go-order-v2      false
    Rule                $app_name ^go-payment-v2$    go-payment-v2    false
    Rule                $app_name ^go-authorizer-v2$ go-authorizer-v2 false


# Debug output for routed records
[OUTPUT]
    Name                stdout
    Match               *
    Format              json


# go-inventory-v2
[OUTPUT]
    Name                kafka
    Match               go-inventory-v2
    Brokers             kafka:29092
    Topics              kfk.logs.go.inventory
    Retry_Limit         False
    Format              json


# go-order-v2
[OUTPUT]
    Name                kafka
    Match               go-order-v2
    Brokers             kafka:29092
    Topics              kfk.logs.go.order
    Retry_Limit         False
    Format              json


# go-payment-v2
[OUTPUT]
    Name                kafka
    Match               go-payment-v2
    Brokers             kafka:29092
    Topics              kfk.logs.go.payment
    Retry_Limit         False
    Format              json


# go-authorizer-v2
[OUTPUT]
    Name                kafka
    Match               go-authorizer-v2
    Brokers             kafka:29092
    Topics              kfk.logs.go.authorizer
    Retry_Limit         False
    Format              json

