[SERVICE]
    Flush 1
    Log_Level info
 
[INPUT]
    Name tail
    Path /var/lib/docker/containers/*/*-json.log
    Tag docker
    Read_from_Head true
 
[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser zap_json
    Reserve_Data On
 
[FILTER]
    Name grep
    Match *
    Regex app_name go-inventory-v2
 
[OUTPUT]
    Name stdout
    Match *
 
[OUTPUT]
    Name kafka
    Match *
    Brokers kafka:29092
    Topics kfk.logs.go.inventory
    Format json