services:

  go-authorizer-v2:
    profiles: ["go-authorizer-v2"]
    container_name: go-authorizer-v2
    build:
      context: ../../go-authorizer-v2
      dockerfile: Dockerfile
    image: go-authorizer-v2:latest
    pull_policy: never
    environment:

      APP_NAME: "go-authorizer-v2"
      VERSION: "2.0"
      ACCOUNT: "local:docker-composer"
      ENV: "dev"
      TYPE: "webserver"

      HTTP_TIMEOUT: "120s"
      HTTP_KEEP_ALIVE: "120s"
      HTTP_READTIMEOUT: "120s"
      HTTP_WRITETIMEOUT: "120s"
      HTTP_IDLECONNTIMEOUT: "120s"
      HTTP_MAXIDLECONNS: "2"
      HTTP_MAXIDLECONNSPERHOST: "2"
      HTTP_MAXCONNSPERHOST: "2"
      HTTP_PORT: "7100"
      READ_BUFFER_SIZE: "12288"
      DISABLE_STARTUP_MESSAGE: "true"

      RSA_PRIVATE_KEY_PATH: "/var/keys/rsa_private_key.pem"
      RSA_PUBLIC_KEY_PATH: "/var/keys/rsa_public_key.pem"
      TOKEN_TTL: "36000s"
      CURRENT_KID: "go-authorizer-v2-key-2026-09"

      # EC256 Keys
      EC256_PUBLIC_KEY_PATH: "/var/keys/ec256/ec256_public_key.pem"
      EC256_KID: "go-authorizer-v2-ec256-key-2026-09"

      DB_HOST: "db-01"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_SCHEMA: "public"
      DATABASE_QUERY_TRACER: "false"
      DB_MAX_CONNS: "5" 
      DB_MIN_CONNS: "5" 
      DB_CONNECTION_TIMEOUT_DURATION: "4s"
      DB_LIFE_TIME_CONNS: "28s"
      DB_IDLE_TIME_CONNS: "1s"

      LOG_LEVEL: "debug"
      LOG_MODE: "json"

      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      OTEL_STDOUT_TRACER: "false"
      OTEL_COLLECTOR: "false"
      OTEL_METRICS_PORT: "8000"

    ports:
      - "7100:7100"
    volumes:
      - ./keys/rsa_private_key.pem:/var/keys/rsa_private_key.pem:ro
      - ./keys/rsa_public_key.pem:/var/keys/rsa_public_key.pem:ro
      - ./keys/ec256/ec256_public_key.pem:/var/keys/ec256/ec256_public_key.pem:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecommerce_network
  
  go-inventory-v2:
    profiles: ["go-inventory-v2"]
    depends_on:
    - go-authorizer-v2
    container_name: go-inventory-v2
    build:
      context: ../../go-inventory-v2
      dockerfile: Dockerfile
    image: go-inventory-v2:latest
    pull_policy: never
    
    environment:
      APP_NAME: "go-inventory-v2"
      VERSION: "2.0"
      ACCOUNT: "local:docker-composer"
      ENV: "dev"
      TYPE: "webserver"

      HTTP_TIMEOUT: "120s"
      HTTP_KEEP_ALIVE: "120s"
      HTTP_READTIMEOUT: "120s"
      HTTP_WRITETIMEOUT: "120s"
      HTTP_IDLECONNTIMEOUT: "120s"
      HTTP_MAXIDLECONNS: "2"
      HTTP_MAXIDLECONNSPERHOST: "2"
      HTTP_MAXCONNSPERHOST: "2"
      HTTP_PORT: "7000"
      READ_BUFFER_SIZE: "12288"
      DISABLE_STARTUP_MESSAGE: "true"

      DB_HOST: "db-01"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_SCHEMA: "public"
      DATABASE_QUERY_TRACER: "false"
      DB_MAX_CONNS: "5" 
      DB_MIN_CONNS: "5" 
      DB_CONNECTION_TIMEOUT_DURATION: "4s"
      DB_LIFE_TIME_CONNS: "28s"
      DB_IDLE_TIME_CONNS: "1s" 

      LOG_LEVEL: "debug"
      LOG_MODE: "json"

      AUTHORIZATION_DRY_RUN: "true"
      AUTHORIZATION_TIMEOUT: "15s"
      AUTHORIZATION_JWKS_URL: "http://go-authorizer-v2:7100/v1/.well-known/jwks.json"
      AUTHORIZATION_HEADER_KEY: "Authorization"
      AUTHORIZATION_REQUIRED_HEADER: "false"
      ALLOWEDSCOPES: "workload01:db-01,workload01:db-02"

      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      OTEL_STDOUT_TRACER: "false"
      OTEL_COLLECTOR: "false"
      OTEL_METRICS_PORT: "8000"

    ports:
      - "7000:7000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecommerce_network

  go-payment-v2:
    profiles: ["go-payment-v2"]
    depends_on:
    - go-authorizer-v2
    container_name: go-payment-v2
    build:
      context: ../../go-payment-v2
      dockerfile: Dockerfile
    image: go-payment-v2:latest
    pull_policy: never
    
    environment:
      APP_NAME: "go-payment-v2"
      VERSION: "2.0"
      ACCOUNT: "local:docker-composer"
      ENV: "dev"
      TYPE: "webserver"

      HTTP_TIMEOUT: "120s"
      HTTP_KEEP_ALIVE: "120s"
      HTTP_READTIMEOUT: "120s"
      HTTP_WRITETIMEOUT: "120s"
      HTTP_IDLECONNTIMEOUT: "120s"
      HTTP_MAXIDLECONNS: "2"
      HTTP_MAXIDLECONNSPERHOST: "2"
      HTTP_MAXCONNSPERHOST: "2"
      HTTP_PORT: "7003"
      READ_BUFFER_SIZE: "12288"
      DISABLE_STARTUP_MESSAGE: "true"

      DB_HOST: "db-01"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_SCHEMA: "public"
      DATABASE_QUERY_TRACER: "false"
      DB_MAX_CONNS: "5" 
      DB_MIN_CONNS: "5" 
      DB_CONNECTION_TIMEOUT_DURATION: "4s"
      DB_LIFE_TIME_CONNS: "28s"
      DB_IDLE_TIME_CONNS: "1s"

      LOG_LEVEL: "debug"
      LOG_MODE: "json"

      AUTHORIZATION_DRY_RUN: "true"
      AUTHORIZATION_TIMEOUT: "15s"
      AUTHORIZATION_JWKS_URL: "http://go-authorizer-v2:7100/v1/.well-known/jwks.json"
      AUTHORIZATION_HEADER_KEY: "Authorization"
      AUTHORIZATION_REQUIRED_HEADER: "false"
      ALLOWEDSCOPES: "workload01:db-01,workload01:db-02"

      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      OTEL_STDOUT_TRACER: "false"
      OTEL_COLLECTOR: "false"
      OTEL_METRICS_PORT: "8000"

      KAFKA_EVENT_DRY_RUN: "true"
      KAFKA_PRODUCER_NAME: 'payment-producer.local'
      KAFKA_PRODUCER_BROKER: "kafka:29092"
      KAFKA_PRODUCER_TOPIC: "payment.topic.01"
      KAFKA_PRODUCER_PROTOCOL: "SASL_PLAINTEXT"
      KAFKA_PRODUCER_MECHANISM: "PLAIN"
      KAFKA_PRODUCER_USERNAME: "admin"
      KAFKA_PRODUCER_PASSWORD: "admin"

    ports:
      - "7003:7003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecommerce_network

  go-order-v2:
    profiles: ["go-order-v2"]
    depends_on:
    - go-authorizer-v2
    container_name: go-order-v2
    build:
      context: ../../go-order-v2
      dockerfile: Dockerfile
    image: go-order-v2:latest
    pull_policy: never
    
    environment:
      APP_NAME: "go-order-v2"
      VERSION: "2.0"
      ACCOUNT: "local:docker-composer"
      ENV: "dev"
      TYPE: "worker"

      HTTP_TIMEOUT: "120s"
      HTTP_KEEP_ALIVE: "120s"
      HTTP_READTIMEOUT: "120s"
      HTTP_WRITETIMEOUT: "120s"
      HTTP_IDLECONNTIMEOUT: "120s"
      HTTP_MAXIDLECONNS: "2"
      HTTP_MAXIDLECONNSPERHOST: "2"
      HTTP_MAXCONNSPERHOST: "2"
      HTTP_PORT: "7001"
      READ_BUFFER_SIZE: "12288"
      DISABLE_STARTUP_MESSAGE: "true"

      DB_HOST: "db-02"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_SCHEMA: "public"
      DATABASE_QUERY_TRACER: "false"
      DB_MAX_CONNS: "5" 
      DB_MIN_CONNS: "5" 
      DB_CONNECTION_TIMEOUT_DURATION: "4s"
      DB_LIFE_TIME_CONNS: "28s"
      DB_IDLE_TIME_CONNS: "1s"

      LOG_LEVEL: "debug"
      LOG_MODE: "json"

      AUTHORIZATION_DRY_RUN: "true"
      AUTHORIZATION_TIMEOUT: "15s"
      AUTHORIZATION_JWKS_URL: "http://go-authorizer-v2:7100/v1/.well-known/jwks.json"
      AUTHORIZATION_HEADER_KEY: "Authorization"
      AUTHORIZATION_REQUIRED_HEADER: "false"
      ALLOWEDSCOPES: "workload01:db-01,workload01:db-02"

      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      OTEL_STDOUT_TRACER: "false"
      OTEL_COLLECTOR: "false"
      OTEL_METRICS_PORT: "8000"

      INVENTORY_ENDPOINT: "http://go-inventory-v2:7000"
      INVENTORY_URL_PATH: "/v1/product"
      INVENTORY_ENDPOINT_TIMEOUT: "10s"

      PAYMENT_ENDPOINT: "http://go-payment-v2:7003"
      PAYMENT_URL_PATH: "/v1/payment"
      PAYMENT_ENDPOINT_TIMEOUT: "10s"

      KAFKA_EVENT_DRY_RUN: "true"
      KAFKA_CONSUMER_NAME: "order-consumer.local"
      KAFKA_CONSUMER_GROUP_ID: "order-consumer-group-01"
      KAFKA_CONSUMER_BROKER: "kafka:29092"
      KAFKA_CONSUMER_TOPIC: "payment.topic.01"
      KAFKA_CONSUMER_PROTOCOL: "SASL_PLAINTEXT"
      KAFKA_CONSUMER_MECHANISM: "PLAIN"
      KAFKA_CONSUMER_USERNAME: "admin"
      KAFKA_CONSUMER_PASSWORD: "admin"

    ports:
      - "7001:7001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecommerce_network

  py-mcp-inventory-v2:
    profiles: ["py-mcp-inventory-v2"]
    depends_on:
    - go-inventory-v2
    container_name: py-mcp-inventory-v2
    build:
      context: ../../py-mcp-inventory-v2
      dockerfile: Dockerfile
    image: py-mcp-inventory-v2:latest
    pull_policy: never
    
    environment:
      VERSION: "0.1"
      ACCOUNT: "local:docker-compose"
      APP_NAME: "py-mcp-inventory-v2"
      PORT: "7500"
      SESSION_TIMEOUT: "700"

      INVENTORY_URL: "http://go-inventory-v2:7000"

      LOG_LEVEL: "INFO"
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      OTEL_STDOUT_LOG_GROUP: "True"
      LOG_GROUP: "/mnt/c/Eliezer/log/py-mcp-inventory-v2.log"
      MCP_VALIDATE_CONTEXT: "false"
    ports:
      - "7500:7500"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecommerce_network
      
  py-mcp-order-v2:
    profiles: ["py-mcp-order-v2"]
    depends_on:
    - go-order-v2
    container_name: py-mcp-order-v2
    build:
      context: ../../py-mcp-order-v2
      dockerfile: Dockerfile
    image: py-mcp-order-v2:latest
    pull_policy: never
    
    environment:
      VERSION: "0.1"
      ACCOUNT: "local:docker-compose"
      APP_NAME: "py-mcp-order-v2"
      PORT: "7501"
      SESSION_TIMEOUT: "700"

      ORDER_URL: "http://go-order-v2:7001"

      LOG_LEVEL: "INFO"
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      OTEL_STDOUT_LOG_GROUP: "True"
      LOG_GROUP: "/mnt/c/Eliezer/log/py-mcp-order-v2.log"
      MCP_VALIDATE_CONTEXT: "false"

    ports:
      - "7501:7501"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecommerce_network

  tei-server:
    profiles: ["tei-server"]
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.6
    container_name: tei-server
    ports:
      - "6500:80"
    networks:
      - ecommerce_network
    volumes:
      - ./data:/data
    # Highlight-start
    command: --model-id BAAI/bge-large-en-v1.5
      
networks:
  ecommerce_network:
    external: true
    name: ecommerce_network